### ISSUE TITLE
LYWSD03MMC no response macOS

### ISSUE THREAD

**Issue by fmpmsilva** [hannseman/homebridge-mi-hygrothermograph#140]
Hi. Got no response in a LYWSD03MMC. This my config:

        {
            "name": "Temperature & Humidity",
            "address": "ae87a9ec-108f-4783-82ab-af6381bb8954",
            "temperatureName": "Temperatura",
            "humidityName": "Humidade",
            "fakeGatoEnabled": false,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "bindKey": "F562f9f730e753cea309072f455755f95",
            "accessory": "Hygrotermograph"
        }

And the logs are:

[3/8/2021, 1:54:23 PM] [Temperature & Humidity] [ae87a9ec108f478382abaf6381bb8954] Discovered peripheral
      Id: ae87a9ec108f478382abaf6381bb8954
      LocalName: LYWSD03MMC
      rssi: -34
      serviceData: 30585b05a9c987ed38c1a408
[3/8/2021, 1:54:23 PM] [Temperature & Humidity] No event

### Versions

- **homebridge**: `homebridge --version`
- **homebridge-mi-hygrothermograph**: `npm list --depth 1 --global homebridge-mi-hygrothermograph`
- **node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by fmpmsilva** [comment]
Also getting:

[3/8/2021, 3:57:14 PM] [Temperature & Humidity] Error: Sensor data is encrypted. Please configure a bindKey.
    at Parser.decryptPayload (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:163:13)
    at Parser.parse (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/parser.js:59:12)
    at Scanner.parseServiceData (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:171:52)
    at Scanner.onDiscover (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:92:25)
    at Noble.emit (events.js:315:20)
    at Noble.onDiscover (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:196:10)
    at NobleMac.emit (events.js:315:20)

**Comment by codyc1515** [comment]
You need to configure a bind key, as per the above message.
