### ISSUE TITLE
Sensor stop working.

### ISSUE THREAD

**Issue by petrocino** [hannseman/homebridge-mi-hygrothermograph#157]
Hi there.

I have a RBPi4 4GB. All packages are at latest version, Homebridge packages as well.

After the last weekend. my homebridge freezes and that's the output that I'm getting from logs:

```
[7/5/2021, 4:54:41 PM] [Temperature & Humidity] Initializing Hygrotermograph accessory...
[7/5/2021, 4:54:41 PM] [Temperature & Humidity] address option is not set. When running multiple sensors this will cause interference. See README for instructions.
[7/5/2021, 4:54:41 PM] Error: ENODEV, No such device
    at Hci.init (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:120:18)
    at NobleBindings.init (/usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:93:13)
    at /usr/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:61:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[7/5/2021, 4:54:41 PM] Got SIGTERM, shutting down Homebridge...
[7/5/2021, 4:54:41 PM] [eWeLink] Child bridge process ended

```

My config section for this plugin is:

```
"accessories": [
    {
        "name": "Temperatura & Humidade",
        "address": "C6:4d:6b:B2:41:BC",
        "temperatureName": "Temperatura",
        "humidityName": "Humidade",
        "fakeGatoEnabled": false,
        "timeout": 15,
        "forceDiscovering": true,
        "forceDiscoveringDelay": 2500,
        "disableBatteryLevel": false,
        "lowBattery": 10,
        "temperatureOffset": 0,
        "humidityOffset": 0,
        "_bridge": {
            "username": "0E:DD:98:AD:43:8B",
            "port": 43126
        },
        "accessory": "Hygrotermograph"
```

It's not the sensor, since it can be found on Mi App

Model on back battery plate: LYWSDCGQ/01ZM

Anyone has clue about this error??

**Comment by hannseman** [comment]
There is something wrong with your setup. No bluetooth device can be found, please check hciconfig and make sure that you've followed the instructions in the README for how to install all dependencies and make sure that non-root users can access bluetooth.
