### ISSUE TITLE
Error: Could not start scanning, state is poweredOff

### ISSUE THREAD

**Issue by chrisremie** [hannseman/homebridge-mi-hygrothermograph#165]
homebridge-mi-hygrothermograph  v3.1.0
Raspberry Pi Zero W
Homebridge 1.3.6
Raspbian Buster Lite (2021-05-07)
Node.js Version: v14.18.1.

This happened after a while of normal behavior.

[18/11/2021, 17:35:15] [TempSquare 2] Error: Could not start scanning, state is poweredOff (not poweredOn)
    at Noble.scan (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:120:21)
    at Noble.startScanning (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:149:10)
    at Scanner.start (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:36:13)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/lib/scanner.js:72:14)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by hannseman** [comment]
poweredOff means that Bluetooth is not running on your system. Make sure that you have a bluetooth compatible system and follow the README on what dependencies you need to install. Make sure you've run `sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)` and try running `hciconfig hci0 up` to to make sure bluetooth is running.
