### ISSUE TITLE
Homebridge restarting ENODEV error

### ISSUE THREAD

**Issue by ethempekin** [hannseman/homebridge-mi-hygrothermograph#177]
My homebridge keeps restarting since 3 weeks. Is it plugin related? 

Here is the error:

```
[14/02/2022, 22:31:46] Error: ENODEV, No such device
    at Hci.init (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:120:18)
    at NobleBindings.init (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:93:13)
    at /usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/noble.js:61:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by ripcurl7777** [comment]
Same Problem here

**Comment by hannseman** [comment]
`ENODEV` is a system error which means that no Bluetooth device can be found on your system. Make sure that you've installed all the pre-requirements described the in the README: https://github.com/hannseman/homebridge-mi-hygrothermograph#installation

Also please paste the output from the `hciconfig` command, it should read something like this:
```
pi@foo:~ $ sudo hciconfig
hci0:	Type: Primary  Bus: UART
	BD Address: AA:BB:CC:DD:EE:FF  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING
	RX bytes:659872570 acl:0 sco:0 events:158616152 errors:0
	TX bytes:2936 acl:0 sco:0 commands:147 errors:0
```

**Comment by chris-008** [comment]
good afternoon,
I have the same issue but I can't install the priviliges to meet the pre requirements, see issue #188.

I also don't get any result with hciconfig?
chris@orangepizero:~$ sudo hciconfig
chris@orangepizero:~$ 


The xiaomi app is showing the device, but bluetooth menu from iPhone doesn't?
Wile retrieving the binding code,  the device is not connected to the Xiaomi app anymore, so how to figure out whether your device is connected or not?

chris@orangepizero:~$ sudo hciconfig
chris@orangepizero:~$
