### ISSUE TITLE
ERROR INITIALIZING PLUGIN homebridge-mi-hygrothermograph

### ISSUE THREAD

**Issue by jjss520** [hannseman/homebridge-mi-hygrothermograph#180]
[5/7/2022, 2:21:38 PM] ERROR INITIALIZING PLUGIN homebridge-mi-hygrothermograph:
[5/7/2022, 2:21:38 PM] Error: EAFNOSUPPORT, Address family not supported by protocol
    at new Hci (/homebridge/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:80:18)
    at new NobleBindings (/homebridge/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)
    at module.exports (/homebridge/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/resolve-bindings.js:13:12)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/index.js:2:51)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

**Comment by bidulle95** [comment]
idem

**Comment by hannseman** [comment]
Looks like you're trying to use this plugin through a Docker container, this is a bit problematic, see the following issues for help:
https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/94
https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/135
