### ISSUE TITLE
shutting down Homebridge ？，Hygrothermograph 2 / LYWSD03MMC

### ISSUE THREAD

**Issue by i7s7x** [hannseman/homebridge-mi-hygrothermograph#184]
**Try removing the entire directory /var/lib/homebridge/node_moduleshomebridge-mi-hygrothermograph and then install.**

not work

**Expected Behavior**

Homebrige should run

**Current Behavior**

Homebrige stops running

**Versions**

- **homebridge**: v1.5.0
- **homebridge-mi-hygrothermograph**: /usr/local/lib
└── homebridge-mi-hygrothermograph@3.3.1
- **node**:       v12.22.12
- **OS**:        "Debian GNU/Linux 11 (bullseye)"

 **Configuration**
{
    "bridge": {
        "name": "Homebridge E77C",
        "username": "0E:D4:DA:DC:E7:7C",
        "port": 51913,
        "pin": "234-09-864",
        "advertiser": "bonjour-hap"
    },
    "accessories": [
        {
            "name": "Temperature & Humidity",
            "type": "Hygrotermograph",
            "address": "a4:c1:38:9f:d3:7a",
            "temperatureName": "Temperature",
            "humidityName": "Humidity",
            "moistureName": "Moisture",
            "fertilityName": "Fertility",
            "illuminanceName": "Illuminance",
            "fakeGatoEnabled": false,
            "timeout": 15,
            "forceDiscovering": true,
            "forceDiscoveringDelay": 2500,
            "disableBatteryLevel": false,
            "lowBattery": 10,
            "temperatureOffset": 0,
            "humidityOffset": 0,
            "moistureOffset": 0,
            "fertilityOffset": 0,
            "illuminanceOffset": 0,
            "bindKey": "3d9b99c8ad66fad4b207d9c1e09c0423",
            "accessory": "Hygrotermograph"
        }
    ],

```

 **Homebridge Log / Command Output**

[2022/7/24 14:04:20] [miot] [Mi LED Desk Lamp 1S] Starting property polling.
[2022/7/24 14:04:22] [Homebridge UI] Homebridge restart request received
[2022/7/24 14:04:22] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[2022/7/24 14:04:22] [Homebridge UI] Sending SIGTERM to Homebridge
[2022/7/24 14:04:22] Got SIGTERM, shutting down Homebridge...
[2022/7/24 14:04:27] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[2022/7/24 14:04:32] [HB Supervisor] Restarting Homebridge...
[2022/7/24 14:04:32] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[2022/7/24 14:04:32] [HB Supervisor] Started Homebridge v1.5.0 with PID: 754
[2022/7/24 14:04:33] Loaded config.json with 1 accessories and 2 platforms.
[2022/7/24 14:04:33] Loaded 6 cached accessories from cachedAccessories.
[2022/7/24 14:04:33] ---
[2022/7/24 14:04:33] Loaded plugin: homebridge-config-ui-x@4.50.0
[2022/7/24 14:04:33] Registering platform 'homebridge-config-ui-x.config'
[2022/7/24 14:04:33] ---
[2022/7/24 14:04:33] Loaded plugin: homebridge-mi-hygrothermograph@3.3.1
[2022/7/24 14:04:36] Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
[2022/7/24 14:04:36] ---
[2022/7/24 14:04:37] Loaded plugin: homebridge-miot@1.2.4
[2022/7/24 14:04:37] Registering platform 'homebridge-miot.miot'
[2022/7/24 14:04:37] ---
[2022/7/24 14:04:37] Loading 2 platforms...
[2022/7/24 14:04:37] [miot] Initializing miot platform...
[2022/7/24 14:04:37] Loading 1 accessories...
[2022/7/24 14:04:37] [Temperature & Humidity] Initializing Hygrotermograph accessory...
[2022/7/24 14:04:37] [miot] Initializing devices
[2022/7/24 14:04:37] [miot] [先锋风扇] Got device configuration, initializing device with name: 先锋风扇
[2022/7/24 14:04:37] [miot] [小米风扇] Got device configuration, initializing device with name: 小米风扇
[2022/7/24 14:04:37] [miot] [插座] Got device configuration, initializing device with name: 插座
[2022/7/24 14:04:37] [miot] [Mi LED Desk Lamp 1S] Got device configuration, initializing device with name: Mi LED Desk Lamp 1S
[2022/7/24 14:04:37] [miot] [浴霸内卫] Got device configuration, initializing device with name: 浴霸内卫
[2022/7/24 14:04:37] [miot] [浴霸外卫] Got device configuration, initializing device with name: 浴霸外卫
Setup Payload:
X-HM://0023UVB9KDS06
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 234-09-864 │     
    └────────────┘     
                       
[2022/7/24 14:04:37] Error: ENODEV, No such device
    at Hci.init (/var/lib/homebridge/node_modules/.pnpm/@abandonware+noble@1.9.2-15/node_modules/@abandonware/noble/lib/hci-socket/hci.js:121:20)
    at NobleBindings.init (/var/lib/homebridge/node_modules/.pnpm/@abandonware+noble@1.9.2-15/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:93:13)
    at /var/lib/homebridge/node_modules/.pnpm/@abandonware+noble@1.9.2-15/node_modules/@abandonware/noble/lib/noble.js:61:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by filipwitek** [comment]
same problem on my end

**Comment by chris-008** [comment]
here as well, any solution so far?

**Comment by chris-008** [comment]
It seems that you should have the device connected so it can be discovered before installing this plugin.
this link might help:

https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/177

**Comment by chris-008** [comment]
anyone has success so far?
