### ISSUE TITLE
Error during startup homebridge

### ISSUE THREAD

**Issue by kiondi** [hannseman/homebridge-mi-hygrothermograph#19]
Hi
I installed the plugin following the instructions, when starting homebridge I have these errors, what problems could I have?
thanks in advance 
Marco

[2018-6-25 14:49:16] Loaded plugin: homebridge-mi-hygrothermograph
[2018-6-25 14:49:17] Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
[2018-6-25 14:49:17] ---
[2018-6-25 14:49:17] Loaded config.json with 1 accessories and 0 platforms.
[2018-6-25 14:49:17] ---
[2018-6-25 14:49:17] Loading 1 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:254:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by hannseman** [comment]
Hi. Could you please paste your homebridge configuration file?

- Hannes

**Comment by kiondi** [comment]
{
	"bridge": {
		"name": "PrimoPiano",
		"username": "FF:FF:11:00:00:01",
		"port": 51826,
		"pin": "111-11-111",
		"manufacturer": "Kiondi",
		"model": "casa",
		"serialNumber": "0.1.0"
	},
	"description": "Termografo",
	"accessories": [
   	{
	"acessory": "Hygrotermograph",
      	"name": "Temperature & Humidity",
      	"timeout": 10,
      	"temperatureName": "Temperature",
      	"humidityName": "Humidity",
      	"fakeGatoEnabled": true
    }
  ]
}

**Comment by hannseman** [comment]
You've misspelled `acessory`. It should be `accessory`.

```json
{
  "bridge": {
    "name": "PrimoPiano",
    "username": "FF:FF:11:00:00:01",
    "port": 51826,
    "pin": "111-11-111",
    "manufacturer": "Kiondi",
    "model": "casa",
    "serialNumber": "0.1.0"
  },
  "description": "Termografo",
  "accessories": [
    {
      "accessory": "Hygrotermograph",
      "name": "Temperature & Humidity",
      "timeout": 10,
      "temperatureName": "Temperature",
      "humidityName": "Humidity",
      "fakeGatoEnabled": true
    }
  ]
}
```

**Comment by kiondi** [comment]
GREAT!!!
thank you!
Marco
