### ISSUE TITLE
Cannot get it to work on Homebridge-config-ui-x

### ISSUE THREAD

**Issue by carlierquentin** [hannseman/homebridge-mi-hygrothermograph#81]
I just can't find my accessories with this version of Homebridge

**Comment by hannseman** [comment]
Interesting, 2.3.2 added support for updating this plugins settings through the homebridge-config-ui-x GUI. @codyc1515 do you have any insight here?

**Comment by carlierquentin** [comment]
Yes but while installing the plugin throws a lot of errors. I'll will uninstall it and install it again, and paste the result here.

**Comment by hannseman** [comment]
@carlierquentin have you got any updates or error logs?

**Comment by iam-Zedgar** [comment]
Same..
error logs:
```[12/7/2019, 11:52:17 AM] Loaded plugin: homebridge-mi-hygrothermograph
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '@abandonware/bluetooth-hci-socket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)```

and homebridge is restarting infinitely

**Comment by hannseman** [comment]
@iam-Zedgar, nah it doesn’t appear to be related to homebridge-config-ui-x. It’s clear from the error message that the module '@abandonware/bluetooth-hci-socket' can’t be found. 

Try uninstalling this plugin and then installing it with `npm install -g --unsafe-perm homebridge-mi-hygrothermograph`. Please look for any errors in the install output, you might be missing some system dependencies required to install bluetooth-hci-socket. Make sure that you’ve read the installation instructions in the README.

**Comment by hannseman** [comment]
Closing this as no logs have been provided by issue opener or responses on my troubleshooting attempts.
