### ISSUE TITLE
Single Device Works - Multiple Devices All Offline

### ISSUE THREAD

**Issue by 400HPMustang** [hannseman/homebridge-mi-hygrothermograph#86]
### Expected Behavior
Given two devices are added into the config when homebridge is running then hommebridge providing current temp/humidity readings from both devices.  HomeKit also accurately reflects readings from both devices.

### Current Behavior
When multiple devices are installed homebridge reports back 32 degrees temperature and 0% humidity for each device. Homekit shows both devices as not responding

### Steps to Reproduce (for bugs)
Install homebridge
install homebridge-mi-hygrothermograph
Add one device to config and restart homebridge
Device is online and accurate reading
Add second device to config and restart homebridge
Both devices are offline and showing wrong temperature and humidity

### Versions

- **homebridge**: 0.4.50
- **homebridge-mi-hygrothermograph**: v2.3.2
- **node**:       12.13.1
- **OS**:         Windows 10 x64

### Configuration

```
                 {
			"accessory": "Hygrotermograph",
			"name": "Bottom Shelf",
			"address": "58:2d:34:36:ae:ef"
		 },
		 {
			"accessory": "Hygrotermograph",
			"name": "Top Shelf",
			"address": "58:2d:34:36:b7:9d"
		 }
```

### Homebridge Log / Command Output

When it works, it looks more like this, with device readings
```
[11/23/2019, 2:44:13 PM] [Bottom Shelf] [58:2d:34:36:ae:ef] Discovered peripheral
      Id: 582d3436aeef
      LocalName: MJ_HT_V1
      rssi: -80
      serviceData: 5020aa0120efae36342d580d1004c200c002
[11/23/2019, 2:44:13 PM] [Bottom Shelf] [58:2d:34:36:ae:ef] Temperature: 19.4C
[11/23/2019, 2:44:13 PM] [Bottom Shelf] [58:2d:34:36:ae:ef] Humidity: 70.4%
```

When it doesn't work, I get no readings
```
[37m[11/23/2019, 2:31:42 PM][0m [36m[HB Supervisor][0m Homebridge Path: C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge
[37m[11/23/2019, 2:31:42 PM][0m [36m[HB Supervisor][0m UI Path: C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\standalone.js
[37m[11/23/2019, 2:31:42 PM][0m [36m[HB Supervisor][0m Started Homebridge with PID: 13188
[37m[11/23/2019, 2:31:42 PM][39m Loaded config.json with 7 accessories and 7 platforms.
[37m[11/23/2019, 2:31:42 PM][39m ---
[37m[11/23/2019, 2:31:42 PM][39m Loaded plugin: homebridge-camera-ffmpeg
[37m[11/23/2019, 2:31:42 PM][39m Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[37m[11/23/2019, 2:31:42 PM][39m ---
[37m[11/23/2019, 2:31:42 PM][39m Loaded plugin: homebridge-config-ui-x
[37m[11/23/2019, 2:31:42 PM][39m Registering platform 'homebridge-config-ui-x.config'
[37m[11/23/2019, 2:31:42 PM][39m ---
[37m[11/23/2019, 2:31:42 PM][39m Loaded plugin: homebridge-magichome-platform
[37m[11/23/2019, 2:31:42 PM][39m Registering platform 'homebridge-magichome-platform.MagicHome-Platform'
[37m[11/23/2019, 2:31:42 PM][39m ---
[37m[11/23/2019, 2:31:42 PM][39m Loaded plugin: homebridge-mi-hygrothermograph
[0;37m[11/23/2019, 2:31:43 PM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.6.3 is listening on :: port 8008[0m
[37m[11/23/2019, 2:31:43 PM][39m Registering accessory 'homebridge-mi-hygrothermograph.Hygrotermograph'
[37m[11/23/2019, 2:31:43 PM][39m ---
[37m[11/23/2019, 2:31:43 PM][39m Loaded plugin: homebridge-octoprint
[37m[11/23/2019, 2:31:43 PM][39m Registering accessory 'homebridge-octoprint.OctoPrint'
[37m[11/23/2019, 2:31:43 PM][39m ---
[37m[11/23/2019, 2:31:43 PM][39m Loaded plugin: homebridge-people
[37m[11/23/2019, 2:31:43 PM][39m Registering platform 'homebridge-people.People'
[37m[11/23/2019, 2:31:43 PM][39m Registering accessory 'homebridge-people.PeopleAccessory'
[37m[11/23/2019, 2:31:43 PM][39m Registering accessory 'homebridge-people.PeopleAllAccessory'
[37m[11/23/2019, 2:31:43 PM][39m ---
[37m[11/23/2019, 2:31:44 PM][39m Loaded plugin: homebridge-ring
[37m[11/23/2019, 2:31:44 PM][39m Registering platform 'homebridge-ring.Ring'
[37m[11/23/2019, 2:31:44 PM][39m ---
[37m[11/23/2019, 2:31:44 PM][39m Loaded plugin: homebridge-roku
[37m[11/23/2019, 2:31:44 PM][39m Registering accessory 'homebridge-roku.Roku'
[37m[11/23/2019, 2:31:44 PM][39m ---
[37m[11/23/2019, 2:31:44 PM][39m Loaded plugin: homebridge-sleepiq
[37m[11/23/2019, 2:31:44 PM][39m Registering platform 'homebridge-SleepIQ.SleepNumber'
[37m[11/23/2019, 2:31:44 PM][39m ---
[37m[11/23/2019, 2:31:44 PM][39m Loaded plugin: homebridge-tplink-smarthome
[37m[11/23/2019, 2:31:44 PM][39m Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[37m[11/23/2019, 2:31:44 PM][39m ---
[37m[11/23/2019, 2:31:44 PM][39m Loading 7 platforms...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Config][39m Initializing config platform...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Config][39m Running in Standalone Mode.
[37m[11/23/2019, 2:31:44 PM][39m [36m[SleepNumber][39m Initializing SleepNumber platform...
[37m[11/23/2019, 2:31:44 PM][39m [36m[TplinkSmarthome][39m Initializing TplinkSmarthome platform...
[37m[11/23/2019, 2:31:44 PM][39m [36m[TplinkSmarthome][39m homebridge-tplink-smarthome v4.0.1, node v12.13.1, homebridge v0.4.50
[37m[11/23/2019, 2:31:44 PM][39m [36m[People][39m Initializing People platform...
[37m[11/23/2019, 2:31:44 PM][39m [36m[People][39m Initializing platform accessory 'Stephen'...
[37m[11/23/2019, 2:31:44 PM][39m [36m[People][39m Initializing platform accessory 'Kevin'...
[37m[11/23/2019, 2:31:44 PM][39m [36m[People][39m Initializing platform accessory 'Tifa'...
[37m[11/23/2019, 2:31:44 PM][39m [36m[People][39m Initializing platform accessory 'Skye'...
[37m[11/23/2019, 2:31:44 PM][39m [36m[People][39m Initializing platform accessory 'Sarah'...
[37m[11/23/2019, 2:31:44 PM][39m [36m[People][39m Initializing platform accessory 'Anyone'...
[37m[11/23/2019, 2:31:44 PM][39m [36m[People][39m Initializing platform accessory 'No One'...
[37m[11/23/2019, 2:31:44 PM][39m [36m[People][39m WebHook: Started server on port '51828'.
[37m[11/23/2019, 2:31:44 PM][39m [36m[Ring][39m Initializing Ring platform...
[37m[11/23/2019, 2:31:44 PM][39m [36m[MagicHome-Platform][39m Initializing MagicHome-Platform platform...
[37m[11/23/2019, 2:31:44 PM][39m [36m[MagicHome-Platform][39m Discovering Devices
[37m[11/23/2019, 2:31:44 PM][39m [36m[MagicHome-Platform][39m Initializing platform accessory 'Humidor LED Strip'...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Camera-ffmpeg][39m Initializing Camera-ffmpeg platform...
[37m[11/23/2019, 2:31:44 PM][39m Loading 7 accessories...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Right Side S5][39m Initializing OctoPrint accessory...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Right Side S5][39m Initialized OctoPrint Accessory at http://10.107.112.97
[37m[11/23/2019, 2:31:44 PM][39m [36m[Left Side S5][39m Initializing OctoPrint accessory...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Left Side S5][39m Initialized OctoPrint Accessory at http://10.107.112.109
[37m[11/23/2019, 2:31:44 PM][39m [36m[Right Side CR-10][39m Initializing OctoPrint accessory...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Right Side CR-10][39m Initialized OctoPrint Accessory at http://10.107.112.38
[37m[11/23/2019, 2:31:44 PM][39m [36m[Left Side CR-10][39m Initializing OctoPrint accessory...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Left Side CR-10][39m Initialized OctoPrint Accessory at http://10.107.112.29
[37m[11/23/2019, 2:31:44 PM][39m [36m[Roku][39m Initializing Roku accessory...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Bottom Shelf][39m Initializing Hygrotermograph accessory...
[37m[11/23/2019, 2:31:44 PM][39m [36m[Top Shelf][39m Initializing Hygrotermograph accessory...
Load homebridge-magichome-platform.MagicHome-Platform
[37m[11/23/2019, 2:31:44 PM][39m [36m[TplinkSmarthome][39m Configuring cached accessory: [Garage Door Right] 8012B4083E093FCC89725E6A7E9AF1181A1B8644 4bacc774-cf00-43be-a716-8002236f1f5f
[37m[11/23/2019, 2:31:44 PM][39m [36m[TplinkSmarthome][39m Configuring cached accessory: [Back Porch] 8012C2D19D666BCA61C2B7D27E432F801A1C23A0 c28c082e-bf2d-4fac-aace-f8ae90d75a16
[37m[11/23/2019, 2:31:44 PM][39m [36m[TplinkSmarthome][39m Configuring cached accessory: [Garage Door Left] 801227BB3C861DD62DACD43F355E92B11A1B218D bd0d4392-b406-4926-a843-170d89f84418
[37m[11/23/2019, 2:31:44 PM][39m [36m[TplinkSmarthome][39m Configuring cached accessory: [Window Lamp] 8006AC52E8FC251605AB2E8118C29BEF19668BF4 7be0558b-e128-43bb-9219-083637345b33
[37m[11/23/2019, 2:31:44 PM][39m [36m[TplinkSmarthome][39m Configuring cached accessory: [Birds Lamp] 8006E8FF6C756D659AE5EA9F49E1A3A5196593C4 94d0f8a3-6c4f-440a-9ddc-03d56ae0685a
[37m[11/23/2019, 2:31:44 PM][39m [36m[TplinkSmarthome][39m Configuring cached accessory: [Lamp Post] 80066D30754D80C4E46FF903F71677A919668A2A 553ec452-e5b4-4ad0-9332-4a48120551c3
[37m[11/23/2019, 2:31:44 PM][39m [36m[TplinkSmarthome][39m Configuring cached accessory: [Front Porch] 8012D7CBCA4218980795E9A2A145DE841A21A370 9fe163f4-f90c-478b-8bac-23ba3cf1c6a1
[37m[11/23/2019, 2:31:44 PM][39m [36m[SleepNumber][39m Configuring Cached Accessory:  bed0privacy UUID:  58e7418e-7eb4-4740-9f1a-4435fd3e6497
[37m[11/23/2019, 2:31:44 PM][39m [36m[SleepNumber][39m Configuring Cached Accessory:  bed0leftSideoccupancy UUID:  5f86b555-bdcd-4ae5-8e11-53c65161a6a0
[37m[11/23/2019, 2:31:44 PM][39m [36m[SleepNumber][39m Configuring Cached Accessory:  bed0leftSidenumber UUID:  c377e834-1a83-4c95-a500-f01cfeda07f4
[37m[11/23/2019, 2:31:44 PM][39m [36m[SleepNumber][39m Configuring Cached Accessory:  bed0rightSideoccupancy UUID:  6585b29b-f0aa-4528-ad1e-5e2bb7489a1d
[37m[11/23/2019, 2:31:44 PM][39m [36m[SleepNumber][39m Configuring Cached Accessory:  bed0rightSidenumber UUID:  985a9807-a671-44f5-96b0-3ba26c2cabf9
Setup Payload:
X-HM://0023ISZBILJ9C
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

[37m[11/23/2019, 2:31:44 PM][39m [36m[Bottom Shelf][39m Stop scanning. (poweredOff)
[37m[11/23/2019, 2:31:44 PM][39m [36m[Top Shelf][39m Stop scanning. (poweredOff)
[37m[11/23/2019, 2:31:44 PM][39m Homebridge is running on port 51826.
```

**Comment by 400HPMustang** [comment]
This has now turned into not finding any bluetooth devices

```
No compatible USB Bluetooth 4.0 device found!
    at BluetoothHciSocket.bindUser (C:\Users\Stephen\AppData\Roaming\npm\node_modules\homebridge-mi-hygrothermograph\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:87:11)
    at BluetoothHciSocket.bindRaw (C:\Users\Stephen\AppData\Roaming\npm\node_modules\homebridge-mi-hygrothermograph\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:43:8)
    at Hci.init (C:\Users\Stephen\AppData\Roaming\npm\node_modules\homebridge-mi-hygrothermograph\node_modules\@abandonware\noble\lib\hci-socket\hci.js:101:35)
    at NobleBindings.init (C:\Users\Stephen\AppData\Roaming\npm\node_modules\homebridge-mi-hygrothermograph\node_modules\@abandonware\noble\lib\hci-socket\bindings.js:82:13)
    at Noble.<anonymous> (C:\Users\Stephen\AppData\Roaming\npm\node_modules\homebridge-mi-hygrothermograph\node_modules\@abandonware\noble\lib\noble.js:57:24)
    at processTicksAndRejections (internal/process/task_queues.js:75:11
	```

**Comment by hannseman** [comment]
I just released a new version (3.0.1) with updates to the bluetooth library. Please give it a shot.

**Comment by hannseman** [comment]
Closing this issue due to no response.

**Comment by 400HPMustang** [comment]
Sorry just got around to this. Running your 3.0.1 plugin and was able to add both devices and they're responding and reporting back accurate temp/humidity. Thank you for the fix.
