### ISSUE TITLE
homebridge not starting after installing the plugin

### ISSUE THREAD

**Issue by flavienhaas** [hannseman/homebridge-mi-hygrothermograph#94]
I'm running homebridge inside a LXC container on my pi 3B+
```
root@homebridge:~# lsmod | grep bt
btbcm                  16384  1 hci_uart
bluetooth             389120  24 hci_uart,bnep,btbcm
```

### Expected Behavior

it looks like the plugin stop homebridge from starting

### Versions

- **homebridge**: `homebridge --version`
```
root@homebridge:~# homebridge --version
0.4.50
```

- **homebridge-mi-hygrothermograph**: `npm list --depth 1 --global homebridge-mi-hygrothermograph`
```
root@homebridge:~# npm list --depth 1 --global homebridge-mi-hygrothermograph
/usr/local/lib
└── homebridge-mi-hygrothermograph@2.4.0 
```

- **node**:       `node --version`
```
root@homebridge:~# node --version
v10.15.2
```

- **OS**:         
```
root@homebridge:~# uname -a
Linux homebridge 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```

### Configuration

```
{
  "name": "TemperatureÂ &Â Humidity",
  "address": "dc:13:73:6c:d1:ba",
  "temperatureName": "Temperature",
  "humidityName": "Humidity",
  "fakeGatoEnabled": true,
  "fakeGatoStoragePath": "/home/homebridge/temphum/",
  "timeout": 15,
  "forceDiscovering": true,
  "forceDiscoveringDelay": 2500,
  "disableBatteryLevel": false,
  "lowBattery": 10,
  "temperatureOffset": 0,
  "humidityOffset": 0,
  "accessory": "Hygrotermograph"
}
```

### Homebridge Log / Command Output

```
[2/19/2020, 7:55:42 PM] Loaded config.json with 1 accessories and 1 platforms.
[2/19/2020, 7:55:42 PM] ---
[2/19/2020, 7:55:42 PM] Loaded plugin: homebridge-config-ui-x
[2/19/2020, 7:55:42 PM] Registering platform 'homebridge-config-ui-x.config'
[2/19/2020, 7:55:42 PM] ---
[2/19/2020, 7:55:42 PM] Loaded plugin: homebridge-mi-hygrothermograph
/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:75
  this._socket = new BluetoothHciSocket();
                 ^

Error: EAFNOSUPPORT, Address family not supported by protocol
    at new Hci (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/hci.js:75:18)
    at new NobleBindings (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:28:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-hygrothermograph/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:511:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by hannseman** [comment]
Hi!

Accessing bluetooth from containers are problematic. I'm not running homebridge in a container so I've never tried to make it work but please have a look at:
https://github.com/moby/moby/issues/16208

Also see these previous issues for this plugin which might help you:
https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/48
https://github.com/hannseman/homebridge-mi-hygrothermograph/issues/92
